# 2026-07-19 — Evaluation/submission stage, docs split, confidence tuning

Three pieces of work: a dedicated GISLR evaluation-and-submission stage (with the schema
change that makes submission tracking a query), the `docs/` logs-vs-reports split, and the
POPSIGN extraction-quality tuning notebook. Plus one measurement that changes how POPSIGN
extraction should be tuned, and one that diagnoses the accuracy plateau.

---

## 1. Two findings worth leading with

### 1.1 The ~73% plateau is overfitting, not underfitting

The first thing the new evaluation notebook produced answers TODO §7.1 step 2 directly.
Train-vs-val accuracy at each run's best epoch:

| run | arch | subset | train acc | val acc | gap |
|---|---|---|---|---|---|
| 1784397301 | bilstm | FP_118/xy | 0.9886 | 0.7526 | **0.236** |
| 1784395799 | bilstm | ME_126/xy | 0.9716 | 0.7503 | **0.221** |
| 1784396516 | bilstm | ME_132/xy | 0.9716 | 0.7476 | **0.224** |
| 1784393064 | gru | ME_126/xy | 0.9022 | 0.7472 | **0.155** |
| 1784399741 | lstm | ME_126/xy | 0.9225 | 0.7453 | **0.177** |

Every model memorizes the training set (90–99%) and generalizes to ~75%. This is `train >> val`
by a wide margin, so the plateau task list's own branch condition says: **prioritize
augmentation and regularization (§7.4) before adding features**. The normalization and motion
work (§7.2/§7.3) is still worth doing on its merits, but it is not what is capping accuracy
today — a model that memorizes 99% of training data is not short of signal.

The BiLSTM gap being the largest is consistent: it has the most capacity (2.7M params) and the
weakest constraint (it can see the future), so it memorizes hardest.

### 1.2 The most-confused class pairs are semantic, not geometric

All 18 registry runs now have canonical evals, so the aggregate confusion matrix averages
over 18 independently trained models spanning 4 architectures. The top confusions:

| true → predicted | mean rate | reverse | | true → predicted | mean rate | reverse |
|---|---|---|---|---|---|---|
| awake → wake | 0.424 | 0.371 | | nap → sleep | 0.209 | 0.064 |
| mouth → lips | 0.309 | 0.226 | | that → stay | 0.205 | 0.149 |
| give → gift | 0.298 | 0.043 | | listen → hear | 0.200 | 0.187 |
| cut → scissors | 0.258 | 0.120 | | kitty → cat | 0.185 | 0.071 |
| goose → duck | 0.239 | 0.075 | | bedroom → bed | 0.161 | 0.054 |
| pencil → pen | 0.225 | 0.158 | | puppy → dog | 0.140 | 0.044 |

These are near-synonyms and morphologically related sign pairs, and several are confused
**symmetrically** (`awake`/`wake` at 0.42/0.37, `mouth`/`lips` at 0.31/0.23, `listen`/`hear` at
0.20/0.19) — i.e. the models cannot tell which of the two it is in either direction. That is a
different problem from "the model can't see the handshape": some of these may be genuinely
near-identical signs, which would place part of the residual error in a **label ceiling**
rather than a feature deficiency.

Combined with §1.1, the picture is: the models memorize training data almost perfectly, and
what they fail on at val time is dominated by semantically adjacent pairs. TODO §7.1 step 5
(inspect example sequences per pair, classify as handshape / motion / location) is now the
highest-value next diagnostic — and it should explicitly allow the verdict "these two signs are
not reliably distinguishable in this data".

### 1.3 Aside: CausalConv1D is not in the same league — *and here is why*

Best accuracy per architecture across the 18 runs: bilstm **0.7525**, gru **0.7471**, lstm
**0.7453**, cnn1d **0.5414**. The plateau framing ("GRU, 1D-CNN, LSTM and BiLSTM all converge
to ~70–74%") does not hold for the CNN — it is ~20 points behind.

> **Resolved later the same day (§6): this was a misconfiguration, not an architecture result.**
> `cnn1d`'s `num_layers` — the number of dilated conv *blocks*, i.e. its receptive field — had
> been flattened from 5 to 2 while hand-syncing the four training notebooks' hyperparameters.
> That cut its context from **125 frames to 13**, on 128-frame sequences. The numbers above are
> from a crippled model; **cnn1d must be re-run before any conclusion is drawn about it**
> (TODO §5.5.1).

---

## 2. GISLR stage 2 — evaluation, export, submission (TODO §6)

New notebook **`src/gislr.2.models.evaluation.ipynb`**; the four training notebooks are now
training drivers and nothing else.

- **Export removed from `gislr.1.model.gru.ipynb`** (its deferred §7, the only training
  notebook that had one) and rehomed in `modules/model/export.py`, arch-generic.
- **DuckDB leaderboard** over `data/models/*/meta.json` — the run records *are* the queryable
  table; `index.csv` is the committed snapshot, not the query path. Ranking metric is
  `COALESCE(overall_accuracy, train_val_acc)`, identical to `build_model_index.py`'s `val_acc`.
- **Learning curves**: best 5 runs overlaid on one figure, plus the train/val gap table above.
- **Confusion matrices**: top 5 individually, then one row-normalized matrix averaged over
  *all* evaluated runs. Averaging normalized matrices weights each model equally; a confusion
  that survives averaging across GRU/LSTM/BiLSTM/CNN is a property of the data, not of an
  architecture.
- **Export + submission** sections, both skip-if-done.

### Supporting module work

- `architectures.py`: every model gains **`forward_full(x)`** — a batch-1, unpacked,
  ONNX-friendly forward. Export asserts it matches the packed training forward before writing
  anything; verified **max |diff| = 0.00e+00 for all four architectures**, xy and xyz.
- `export.py`: parity check → ONNX → TF SavedModel → TFLite → validation with the grader's
  exact calling convention (NaNs included) → `submission.zip`. NaN→0, the landmark gather and
  the z-drop for xy runs all live *inside* the exported graph, so raw `(T, 543, 3)` frames work
  for every run regardless of subset or coordinate config.
- `submission.py`: the queue as a query, plus the Kaggle call.
- `eval_gru.py` refactored so **`evaluate_run(run_dir)` is importable** (the CLI is now a thin
  wrapper) and now writes **`assets/val_predictions.npz`** — every confusion matrix derives
  from that file, so inference runs once per run, ever.
- `train.py` writes `assets/history.json` every epoch; `report.load_history` falls back to
  `last.pt` and backfills for older runs.

### meta.json schema v3 — the `submission` block

Kaggle allows 100 submissions/day and every trained model should eventually be scored, so
"which models still need submitting" must be a query, not something remembered:

```sql
dataset = 'gislr' AND submission.tested = false   ORDER BY accuracy DESC   LIMIT 100
```

The block is deliberately **dataset-agnostic** — `tested` means "scored on the
official/held-out test set", with `platform` distinguishing `"kaggle"` from `"local"`. No
Kaggle vocabulary in the required keys, so POPSIGN runs reuse it unchanged. `write_meta`
protects the block from the training loop's per-epoch rewrites (the same protection canonical
metrics already had), and `migrate_all` backfilled all **18 existing runs** to v3.

**Open**: `asl-signs` is a *code competition* — the submit command takes `-k <kernel> -v
<version>`, i.e. submission goes **through a Kaggle kernel**, so each model's zip must be
attached to a kernel version. The submit cell therefore defaults to `DRY_RUN = True` and prints
the exact commands until that loop has been walked once by hand.

### The export route: ONNX abandoned, native Keras rebuild instead

The first submission attempt produced nothing, for a mundane reason (the queue skips runs with
no `submission.zip`, and export hadn't been run) — but running export then exposed that the
**PyTorch → ONNX → `onnx2tf` → TFLite** route does not work for these models. Five distinct
failures, in order:

1. `onnx2tf` declares **no dependencies of its own** — needs `tf-keras`, `onnx-graphsurgeon`,
   `sng4onnx`, `ai-edge-litert` at runtime.
2. `torch.nan_to_num`'s infinity handling emits an ONNX **`IsInf`** op it cannot convert.
3. It permutes 3D input layouts, emitting a model that wants `(T, 3, 543)`.
4. **Op coverage**: only **lstm** converted. **gru** died inside onnx2tf's own GRU handler
   (`tf.split(tR, 3)` on a 256-dim, expecting 768), **bilstm** on "mixed types to Tensor",
   **cnn1d** on a squeeze.
5. The one arch that converted then failed TFLite conversion on a malformed `Squeeze` onnx2tf
   itself generated.

Replaced with `modules/model/keras_export.py`: each architecture is rebuilt with **native Keras
layers** and the trained PyTorch weights transferred. All four now export, all under the cap:

| arch | tflite | keras parity | tflite parity |
|---|---|---|---|
| gru | 3.44 MB | 4.1e-06 | 3.8e-06 |
| lstm | 4.48 MB | 3.5e-06 | 3.8e-06 |
| bilstm | 11.06 MB | 3.2e-06 | 2.9e-06 |
| cnn1d | 2.89 MB | 6.1e-06 | 5.4e-06 |

This trades a *conversion* problem for a *weight-transfer* problem — a gate-order or
bias-convention mistake would convert cleanly and predict garbage — so export is gated on two
parity checks and writes nothing if either fails: the Keras rebuild vs `forward_full`, and the
**final .tflite file** vs PyTorch through the entire deployed path (raw `(T, 543, 3)` frames
with NaNs). Conventions that had to be handled: GRU gate reorder `[r,z,n]`→`[z,r,h]` with
`reset_after=True`, LSTM's two biases summed into Keras' one, LayerNorm epsilon forced to
PyTorch's 1e-5 (Keras defaults to 1e-3), Conv1d `(out,in,k)`→`(k,in,out)`.

The second gate immediately earned its keep, catching two bugs:

- **int8 quantization**: `tf.lite.Optimize.DEFAULT` (inherited from the original notebook code,
  "helps with the 40MB cap") shifted logits by ~1e-1. These models are 3–11 MB against a 40 MB
  cap, so it bought nothing and cost accuracy — now off by default.
- **Uninitialized resource variables**: saving the Keras-backed module directly produced a
  TFLite model that died at invoke with `READ_VARIABLE ... variable != nullptr` inside the RNN's
  WHILE loop. Weights are now frozen to constants; and since freezing via
  `from_concrete_functions` loses the output *name* the grader indexes by (`output["outputs"]`),
  the frozen function is re-wrapped in a module that re-declares the exact signature.

`onnx`, `onnx2tf`, `onnxruntime`, `onnx-graphsurgeon`, `sng4onnx`, `ai-edge-litert` and
`tf-keras` were all removed from `pyproject.toml`; `kaggle` added.

---

## 3. `docs/` — logs vs reports

`daily/`, `weekly/` and `reports/` were three siblings for two kinds of document. Now:

```
docs/logs/{daily,weekly}/   # time-ordered: what happened when
docs/reports/<topic>.md     # standalone: what a test or analysis found
```

Moved with `git mv` (history preserved); every reference in `README.md`, `CLAUDE.md`,
`TODO.md`, the notebooks and the existing logs was updated. Convention in `docs/README.md`:
if it's "what I did on this date" it's a log; if it's "what this experiment concluded" it's a
report, and the daily log links to it rather than restating it.

---

## 4. POPSIGN extraction confidence tuning (TODO §2.3)

New notebook **`src/popsign.0.dataset.confidence-tuning.ipynb`** + two modules
(`quality.py`, `overlay.py`). Sample: 50 videos = 5 classes × 10, seeded, globbed straight off
the raw video drives — deliberately **not** dependent on the missing manifests (§0.4/§2.2), so
it is unblocked today. Sampling verified: 50 clips drawn from 124 available classes across all
four train parts.

### The finding that reshaped the notebook

The obvious grid — sweep `min_hand_landmarks_confidence`, since the hands carry the sign — is
**useless**. Driving each field to both extremes on one clip:

| field | 0.01 → 0.99 |
|---|---|
| `min_hand_landmarks_confidence` | **bit-identical output** (inert) |
| `min_pose_{detection,landmarks}_confidence` | hand detection rate **0.52 → 0.09** |
| `min_face_{detection,landmarks}_confidence` | face lost entirely at 0.99 (91% NaN) |

Holistic derives hand ROIs from the **pose** landmarks, so the pose thresholds are what
actually gate the hands. Sweeping the hand threshold would have produced a table of identical
rows and read as "tuning doesn't matter". The grid now sweeps pose thresholds (jointly and one
at a time) plus a face-off arm.

Also corrected against the real API: there is **no** `min_tracking_confidence` and no separate
hand *detection* threshold — the actual field list is `extraction.CONFIDENCE_FIELDS`, and
unknown keys now assert rather than being silently ignored.

### Quality measurement

No ground truth exists for POPSIGN, so everything is a labelled **proxy**: per-group detection
rate, hand-presence rate, longest detection gap, frame-to-frame jitter, and rigid-bone
(shoulder→elbow) length CV. Composite `quality_score` z-scores them across the sweep with
tunable weights — a *relative* ranking of the configs tried, not an absolute measure.

The visual test is weighted **80 worst / 10 median / 10 best** frames, because a bad config's
best frames still look fine; how it *fails* is the informative part. A detector that
confidently tracks the wrong region scores well on every proxy, which is exactly why the
numbers don't get the last word.

Chain smoke-validated end to end (2 configs × 2 videos → npz → metrics → overlays → contact
sheet). **Open caveat**: `pose_rate` was 1.0 in every arm including `min_pose_* = 0.99`, so
that proxy can't currently discriminate pose quality — filed as a follow-up.

### First sweep results — and why the sweep should pause

Two of the seven arms have now been extracted over the full 50-video sample (`default`
50/50, `pose_strict` 49/50). Written up in full at
**[docs/reports/confidence-tuning.md](../../reports/confidence-tuning.md)**; the short
version is that the thresholds are not the story.

**Thresholds barely move anything.** Paired over the 49 videos both configs extracted,
`pose_strict` (pose fields 0.7) costs 0.022 of any-hand detection rate versus `default`
(all fields 0.5) — worse on 31 videos, better on 5 — and buys 0.002 less hand jitter.
Consistent with §"the finding that reshaped the notebook": a stricter pose gate suppresses
marginal hand detections rather than improving them. `default` leads the composite score
(0.160 vs −0.163), but with two arms in the table that score is ±1 by construction, so it's
directional only.

**The proxies are largely measuring clip padding.** Mean any-hand rate of 0.427 reads as
"MediaPipe fails on more than half the frames". It doesn't. Hand presence against normalized
clip position peaks at **0.86** mid-clip and sits at 0.12–0.19 across the first and last
fifths; the median clip's first hand detection is at 27% of its duration and its last at 72%.
Measured between the first and last hand-bearing frame, the same extraction scores **0.85
mean / 0.94 median**. `longest_gap_frames` correlates with `n_frames` at **rho 0.84** — the
"longest detection gap" proxy is very largely a measurement of the lead-in/lead-out.

So the effect being ranked (~0.02) is an order of magnitude below the artifact contaminating
the ranking (~0.4). Running the remaining five arms against these proxies would rank them
partly on clip-length variation within the sample. **Fix the measurement window first**
(restrict the proxies to the signing span), drop the constant `pose_rate` term, *then* run
the rest — ~250 extractions, ~25 min at 19 workers.

**A separate deficiency, bigger than any threshold**: only **1.1%** of frames carry both
hands (left 9.5%, right 34.3%), and `hand_rate` tops out at exactly 0.50 across the whole
sample — the signature of "exactly one hand, always". Several sampled signs (`car`, `bath`)
are two-handed in ASL. That is about *which* landmarks holistic returns, and no confidence
threshold in the grid addresses it. It needs the overlay frames looked at, not more tuning.

Downstream consequence worth carrying forward: any temporal model on POPSIGN will see ~50%
non-signing frames per clip. Trimming belongs in the POPSIGN feature-building stage.

---

## 4b. POPSIGN extraction driver — it runs in the notebook after all (TODO §2.3)

This went through a full reversal in one day, and the reversal is the interesting part.

**First pass**: `popsign.0.dataset.extraction.ipynb` was given a CLI handoff
(`modules/scripts/extract_popsign.py`) on the strength of the pre-existing "multiprocessing
can't run in a Jupyter kernel on Windows" note, whose stated mechanism was *spawn re-imports
`__main__`, which in a notebook is the kernel*.

**That mechanism is wrong.** `multiprocessing.spawn.get_preparation_data` only sets
`main_path` when `__main__` has a `__file__` — a kernel has none, so the child never
re-imports `__main__` at all. `sys_path` *is* propagated, and this project's worker functions
live in an importable module (`_extract_one`, `_init_worker`), not in a cell. The classic
Jupyter+spawn failure is about workers **defined in the notebook**; ours never were.
Confirmed by driving a real ipykernel over ZMQ: the pool ran 4 videos on 2 workers, 0 failed,
**21.6 s — the same wall time as the CLI**, through the very resolution sequence that had
deadlocked. The guard is gone.

The hang that motivated it was real, but it is far better explained by the leaked-graph
deadlock above, which produces exactly that signature and which the pool cannot detect.

**The one objection that survived** was concrete and worth fixing rather than routing around:
MediaPipe logs from C++ (absl/glog) straight to file descriptor 2, and ipykernel captures
fd-level output into cell output by default (`IPKernelApp.capture_fd_output = True`). A
30K-video run would have written hundreds of `oneDNN`/`XNNPACK`/`inference_feedback_manager`
lines *per worker* into the `.ipynb` — precisely the failure mode that once left a 17 MB
notebook in this repo (§0.2). So `_init_worker` now redirects each worker's fd 2 to
`<out_dir>/<split>/_worker_stderr.log` before MediaPipe is imported: the messages stay
readable on disk and out of the notebook.

**Verified by executing the notebook's own cells** in a real ipykernel — setup → manifest
generation → verification → pilot → ETA → cleanup:

| | |
|---|---|
| pilot trials | 2 (shrunk for the test), 0 failed |
| cell-output noise lines | **0** |
| total cell output | ~2 KB |
| worker logs | captured to `_worker_stderr.log` |

`extract_popsign.py` stays as an **optional** CLI for unattended runs that should outlive the
kernel. Both share the manifests and are resumable, so they are interchangeable.

The lesson worth keeping: a plausible mechanism attached to a real symptom is not a
diagnosis. The "can't run in Jupyter" story explained the observation, was repeated into four
documents and a runtime guard, and was wrong — while the actual bug (a leaked native graph)
sat undetected until a pilot hung and the process table was actually looked at.

The chosen confidence config is now an explicit notebook constant threaded into the script
(`--confidence`), so the bulk run records which thresholds produced its output rather than
silently inheriting MediaPipe's defaults.

One bug worth recording because verifying the handoff cells *by printing them* could not
catch it: the shared options (`--confidence`, `--cpu-fraction`, `--ram-limit-pct`) were
defined only on the top-level parser, so the command the cells print — which puts them after
the subcommand, as anyone naturally would — died with `unrecognized arguments`. They are now
attached to the subparsers as well, with `SUPPRESS` defaults on the copies so a subparser
cannot clobber a value given before the subcommand. Both positions parse, and the
before/after override precedence is tested.

### The first pilot deadlocked — leaked MediaPipe graphs

The first real pilot run stalled at **18/20 with every worker at 0% CPU** and no error. The
diagnosis, from live process inspection rather than from any traceback:

1. POPSIGN **mixes resolutions** — 19 of the 20 trial videos are 1944×2592, one (`drink`) is
   1080×1920.
2. The worker keeps **one persistent `HolisticLandmarker`** across videos. The graph's
   segmentation-smoothing calculator compares each frame with the previous one, so the
   resolution change raises `INTERNAL: RET_CHECK failure ... current_mat->rows ==
   previous_mat->rows (1920 vs. 2592)` — twice, entering and leaving that video.
3. The per-frame `except` handler rebuilt the landmarker by **rebinding `_LANDMARKER` without
   calling `.close()`**. Each `HolisticLandmarker` owns a native graph with ~70 threads, so
   every rebuild leaked one.
4. Evidence: the wedged worker sat at **219 threads / 1.3 GB** against 76 threads / 614 MB for
   its five siblings — about three leaked graphs. It then stopped making progress entirely.
5. `imap_unordered` cannot detect this. The process is *alive*, just never returning, so the
   pool waits forever. Extrapolated to the real run, an overnight 30K-video extraction would
   have hung silently.

Fixes, all in `extraction.py`:

- **`_reset_landmarker()`** closes the old landmarker before building a new one — the leak.
- **Proactive rebuild on resolution change**, checked once per video from
  `CAP_PROP_FRAME_WIDTH/HEIGHT`, so a mixed-resolution dataset no longer takes the per-frame
  exception path at all.
- **`maxtasksperchild=64`** recycles workers as a safety net, since a fresh process is the one
  guaranteed way to reclaim whatever a long-lived graph accumulated.

Verified on the exact failure sequence (2592 → 1920 → 2592, ending on the two videos that
hung): **4/4 extracted in 21.7 s, 0 failed**, frame counts and NaN fractions as expected.

Related, and fixed at the same time: `extract_popsign.py pilot` now **clears the temp tree
before benchmarking**. `extract_dataset` skips already-extracted videos, so leftover npz from
an interrupted pilot would have made a trial time ~0 videos and report a meaningless
throughput — exactly the situation this stall left behind (18 npz on disk).

Two things this casts doubt on. First, the pre-existing "multiprocessing can't run in Jupyter"
diagnosis: `main_path` is only put in the child's preparation data when `__main__` has a
`__file__`, which a kernel lacks, so the child never re-imports `__main__`, and a `Pool` with
module-level workers *does* start (verified). The observed 30-minute hang was real but the
stated cause is wrong — and a leaked graph wedges a worker in exactly the same silent way, so
that may have been this bug all along. The guard stays (running as a script is right
regardless: log volume, kernel restarts, multi-hour runs) but is now labelled empirical.
Second, `pose_strict` finishing at **49/50** in the confidence sweep is suspicious in the same
way, and is the likeliest explanation for that missing video.

### Manifests regenerated — the pilot is unblocked

The other half of the blocker (TODO §0.4) is gone: §1 of the notebook now **generates** the
video manifests rather than assuming they exist. Both splits are laid out
`<root>/<sign>/<sign>/<id>.mp4`, so label = parent directory and id = file stem — the same id
the extraction manifest and the confidence-tuning sample already key on. Regenerated and
verified:

| split | videos | labels | ids unique | spot-check |
|---|---|---|---|---|
| train | 30,867 | 72 | yes | 25/25 paths exist |
| test | 33,600 | **250** | yes | 25/25 paths exist |

Exactly reproduces the pre-restructure counts. The generator asserts id uniqueness *and*
cross-checks every label against the sign encoded in its filename, so a directory-layout
change fails loudly instead of yielding a manifest with silently wrong labels. It is guarded
by `FORCE_REGENERATE` and skips when both CSVs exist — which is also what stops a
top-to-bottom run from ever calling `resolve_datasets()` (the previous scratch cell called it
unconditionally).

**The 72-vs-250 asymmetry is worth stating plainly**: three of the four POPSIGN train parts
(~650GB) are still not downloaded, so **178 of the 250 test labels have no train videos**.
Extracting the full test split is still right — landmarks are cheap and never need redoing —
but only 72 classes are trainable until those parts land.

---

## 6. Training consolidation — four notebooks into one, hyperparameters into a config

The four `gislr.1.model.<arch>.ipynb` notebooks each carried their own `HYP` dict. Since "all
else identical" is the entire premise of the architecture comparison and the subset ablations,
keeping them in sync was both a chore and a correctness requirement — a bad combination.

Replaced by **`src/gislr.1.models.training.ipynb`** (shared setup / config / split / feature
caches, then one section per architecture, then comparison + eval handoff) with every
hyperparameter in **`src/config/gislr.training.json`**, read at run time by
`modules/model/config.py`. Architectures inherit the `shared` block and may deviate only via an
explicit `overrides` entry, which §2 of the notebook prints — so a deviation is visible instead
of being something you find by diffing four files. Validation rejects unknown architectures,
unknown per-arch keys, missing required hyperparameters, bad `coords`, a wrong schema version,
and — the important one — an override naming a key that isn't in `shared`, so a typo like
`lr_patiance` can't quietly become a setting that does nothing. All six failure modes tested.

### What the consolidation immediately caught

Diffing the working tree against `HEAD` before deleting the old notebooks turned up an
uncommitted change that explains §1.3:

**`cnn1d`'s `num_layers` had been changed from 5 to 2** as part of making all four `HYP` dicts
identical. For the recurrent models that parameter is the number of stacked layers, and 2 is
correct. For `CausalConv1D` it is the number of **dilated conv blocks**, which *is* the
receptive field:

```
receptive field = 1 + (kernel - 1) * Σ 2^i
  5 blocks (dilations 1,2,4,8,16) → 125 frames   ≈ MAX_SEQ_LEN = 128
  2 blocks (dilations 1,2)        →  13 frames
```

A 13-frame window on a 128-frame sequence cannot see a whole sign. The 0.54 scores are a
crippled model, not a verdict on 1D convolutions — and the same well-meaning sync that unified
the hyperparameters is what broke it, which is precisely the failure mode the consolidation was
meant to prevent. Restored as an explicit `overrides: {"num_layers": 5}` with the reasoning in
the config's `notes` field; parameter count goes 717K → 1.70M. **cnn1d needs re-running.**

### Also fixed

- Runs written by a Jupyter kernel holding a **stale import** of `train.py` lacked the schema-v3
  `submission` block (7 of them), which broke `save_learning_curves`. `registry.load_meta` now
  normalizes that known v2→v3 gap on read — a run written before submission tracking existed
  has by definition never been submitted — while still letting anything else missing trip the
  schema assertion.
- `report.comparison_row` gained `finished`, and the comparison section now separates
  interrupted runs from finished ones. A BiLSTM run stopped at epoch 12 was otherwise
  indistinguishable from a genuinely bad result.

### Best results so far (training-loop val accuracy, 28 runs)

The newer runs at batch 1024 / lr 1.414e-3 improved on the earlier batch-512 numbers:

| arch | subset | val acc | note |
|---|---|---|---|
| gru | ME_126/xy | **0.7566** | best overall; previous best 0.7472 |
| bilstm | FP_118/xy | 0.7526 | offline-only reference |
| gru | FP_118/xy | 0.7506 | |
| gru | ME_132/xy | 0.7495 | |
| lstm | ME_126/xy | 0.7460 | |
| cnn1d | — | 0.54 | invalid, see above |

---

## 4c. Bulk test-split extraction is running — and the on-disk format, confirmed

The first real bulk run started **13:43 UTC** and is still going as this is written.

| | |
|---|---|
| split | `test` (33,600 videos, 250 labels) |
| progress | **15,549 done / 1 failed**, 247 class folders created |
| throughput | **1.46 videos/s** wall · mean **5.46 s** per video per worker |
| clip length | mean **67.1** frames |
| elapsed / ETA | 2.97 h · **~3.5 h remaining** |
| output root | `src/data/raw/popsign/test/` — `POPSIGN_LANDMARKS_DRIVE` is still unset (§0.6) |

The single failure is `gtsignstudy4a.8035-into-…-0`: `cv2` cannot open the source mp4. That is
a source-file problem, not an extraction bug, and the manifest pattern retries `failed`
entries on the next run, so it needs no intervention now — but it is worth checking whether
that file is truncated on disk once the run finishes.

Two things this run confirms that only a real bulk run could. The **resolution-change fix
holds at scale**: 15.5K videos through a dataset known to mix 1944×2592 and 1080×1920, with
zero deadlocks — the failure mode that killed the first pilot at 18 videos. And the **fd-2
redirect works**: worker C++ logging is in `_worker_stderr.log`, not in any cell output.

### The saved format

Recorded here because it is the contract every downstream POPSIGN stage depends on. One
`np.savez_compressed` archive per video, **the label carried by the path, not stored inside**:

```
<root>/data/raw/popsign/<split>/<label>/<video_id>.npz
```

| key | shape | dtype | meaning |
|---|---|---|---|
| `landmarks` | `(T, 543, 3)` | `float16` | normalized x, y, z — **NaN where undetected** |
| `fps` | scalar | `float32` | source fps (30.0 assumed when cv2 reports 0) |
| `num_frames` | scalar | `int32` | `T` |

Row order is GISLR holistic order — face `0–467`, left hand `468–488`, pose `489–521`, right
hand `522–542` — which is the whole point: `modules.dataset.landmark.subsets` indices (ME-126,
FP-118, …) apply to POPSIGN **unchanged**, so the subset work from 07-15/07-16 transfers
without a remapping layer.

Verified on the first completed file (`test/after/gtsignstudy4a.8032-after-2023_01_23_20_48_48.320-0.npz`):
64 frames @ 29.92 fps, 7.1% NaN overall, 163 KB on disk. At ~165 KB/video the full test split
projects to **~5.4 GB**.

### `popsign.0.dataset.output-inspection.ipynb` (new)

A standalone diagnostic for exactly this question — *what does an extracted sign look like on
disk?* — built to be **safe to run against a live extraction**: no writes anywhere in the
landmarks tree, no worker pool, no MediaPipe import, and `.tmp.npz` staging files excluded
from sampling so a half-written video can never be opened. It reads `_manifest.json` as a
snapshot for progress, opens one completed npz, prints the schema and per-group detection
rates, plots a frame plus a presence timeline, and ends with the reference
npz→model-input loader (NaN→0, subset gather, uniform subsample to 128) mirroring
`modules/model/data.py`.

---

## 5. Status / next

- Canonical evals: **18/18 runs done** — leaderboard, confusion matrices and the plateau
  diagnosis all rest on the full registry.
- **Export is working for all 18 runs' architectures**; §7 of the evaluation notebook must be
  run before §8, since the submission queue skips runs without a `submission.zip`.
- The remaining unknown on submission is the Kaggle **kernel** mechanics (`-k`/`-v`), not our
  pipeline — walk one command through by hand, then set `DRY_RUN = False`.
- **Run** the confidence-tuning sweep (~7 configs × 50 videos), pick a config, then bulk
  extraction.
- Plateau work now has a direction: **§7.4 augmentation/regularization first**, on the
  overfitting evidence above.
- **Bulk test-split extraction running** — 15,549/33,600 at time of writing, ~3.5 h to go
  (§4c). Check the 1 failed video's source file when it finishes, then start `train`.

Week summary: [docs/logs/weekly/2026-30.md](../weekly/2026-30.md).
